feat: add open api doc (#129)
fix remove https from url

diff --git a/.github/workflows/update-homarr-openapi.yaml b/.github/workflows/update-homarr-openapi.yaml
--- a/.github/workflows/update-homarr-openapi.yaml
+++ b/.github/workflows/update-homarr-openapi.yaml
@@ -9,11 +9,14 @@ permissions:
   contents: write
 
 jobs:
-  update-api-spec:
+  start-homarr-and-export-api-spec:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: [20]
     steps:
       - uses: actions/checkout@v4
-        name: "Checkout source repository"
+        name: "Checkout app source repository"
         with:
           repository: homarr-labs/homarr
       - uses: pnpm/action-setup@v2
@@ -27,17 +30,54 @@ jobs:
           cache: 'pnpm'
       - run: pnpm install
         name: "Install dependencies"
-      - run: pnpm docker:dev
-        name: "Start development docker containers"
-      - run: pnpm dev
-        name: "Start development server"
+      - run: pnpm dev > server.log 2>&1 &
+        working-directory: apps/nextjs
+        env:
+          TURBO_TELEMETRY_DISABLED: 1
+          DISABLE_TELEMETRY: 1
+        name: "Start development server in background"
+      - name: "Wait for server to be ready"
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:3000/api/openapi -o /dev/null; then
+              echo "Server is up!"
+              break
+            fi
+            echo "Waiting for server to start..."
+            sleep 3
+          done
+
+          if [ "$i" -eq 30 ]; then
+            echo "Server failed to start within timeout."
+            cat docker.log
+            exit 1
+          fi
       - name: "Fetch OpenAPI specification from development server"
-        run: wget https://localhost:3000/api/openapi
-      - name: "Move OpenAPI json schema to target directory"
-        run: mv openapi /static/api/open-api-schema.json
+        run: wget http://localhost:3000/api/openapi
+      - name: "Rename OpenAPI spec"
+        run: mv openapi openapi.json
+      - uses: actions/upload-artifact@master
+        with:
+          name: api-specification
+          path: openapi.json
+
+  update-api-spec:
+    runs-on: ubuntu-latest
+    needs: start-homarr-and-export-api-spec
+    steps:
+      - uses: actions/checkout@v4
+        name: "Checkout documentation source repository"
+        with:
+          repository: homarr-labs/documentation
+      - uses: actions/download-artifact@master
+        with:
+          name: api-specification
+          path: openapi.json
+      - name: "Move file to target directory"
+        run: mv openapi.json ./static/api/open-api-schema.json
       - uses: EndBug/add-and-commit@v9
         with:
           add: './static/api/'
           default_author: github_actor
-          message: '(chore): update contributors'
+          message: 'chore(api-spec): update OpenAPI spec'
           push: true
